# tasks to complete before running roles
- hosts: localhost
  tags: always
  become: true
  pre_tasks:
    - name: add vscodium apt-key
      apt_key: 
        url: https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg
        state: present   
    - name: pre-run ensure vscodium repo
      apt_repository:
        repo: "deb https://paulcarroty.gitlab.io/vscodium-deb-rpm-repo/debs vscodium main"
        state: present
    - name: Debian unstable (for vbox-guest additions)
      apt_repository:
        repo: deb http://deb.debian.org/debian/ {{ ansible_lsb.codename|lower }} main contrib non-free
        state: present
    - name: pre-run | update package cache (debian, etc)
      tags: always
      apt: update_cache=yes
      changed_when: False

# packages
- hosts: localhost
  become: true
  tasks:
  - name: git
    apt: name=git state=latest
  - name: kde
    apt: name=task-kde-desktop state=latest
  - name: mariadb-server
    apt: name=mariadb-server state=latest
  - name: mariadb-client
    apt: name=mariadb-client state=latest
  - name: VS Codium
    apt: name=codium state=latest
  - name: VBox Guest Additions (X11)
    apt: name=virtualbox-guest-x11 state=latest
  - name: VBox Guest Additions (DKMS)
    apt: name=virtualbox-guest-dkms state=latest

    # end of run cleanup and reporting
- hosts: localhost
  become: true
  tasks:
  - name: cleanup package cache (debian, etc)
    tags: always
    apt:
      autoclean: yes
    changed_when: false

  - name: autoremove orphan packages (debian, etc)
    tags: always
    apt:
      autoremove: yes
      purge: yes
