# tasks to complete before running roles
- hosts: localhost
  tags: always
  become: true
  pre_tasks:
    - name: pre-run ensure MS repo
      apt_repository:
        repo: "deb [arch=amd64,arm64,armhf signed-by=/usr/share/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main"
        state: present
    - name: pre-run | update package cache (debian, etc)
      tags: always
      apt: update_cache=yes
      changed_when: False

# packages
- hosts: localhost
  become: true
  tasks:
  - name: git
    apt: name=git state=latest
  - name: kde
    apt: name=task-kde-desktop state=latest
  - name: mariadb-server
    apt: name=mariadb-server state=latest
  - name: mariadb-client
    apt: name=mariadb-client state=latest
  - name: VS Code
    apt: name=code state=latest
  - name: VBox Guest Additions
    apt: name=virtualbox-guest-utils state=latest

# end of run cleanup and reporting
- hosts: localhost
  become: true
  tasks:
  - name: cleanup package cache (debian, etc)
    tags: always
    apt:
      autoclean: yes
    changed_when: false

  - name: autoremove orphan packages (debian, etc)
    tags: always
    apt:
      autoremove: yes
      purge: yes
