# tasks to complete before running roles
- hosts: localhost
  tags: always
  become: true
  pre_tasks:
    - name: add vscodium apt-key
      apt_key: 
        url: https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg
        state: present   
    - name: pre-run ensure vscodium repo
      apt_repository:
        repo: "deb https://paulcarroty.gitlab.io/vscodium-deb-rpm-repo/debs vscodium main"
        state: present
    - name: Debian unstable (for vbox-guest additions)
      apt_repository:
        repo: deb http://deb.debian.org/debian/ sid main contrib non-free
        state: present
    - name: Install Proton Repo
      apt:
        deb: https://repo.protonvpn.com/debian/dists/stable/main/binary-all/protonvpn-stable-release_1.0.4_all.deb
    - name: add brave apt-key
      apt_key:
        url: https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
        state: present
    - name: add brave repo
      apt_repository:
        repo: "deb https://brave-browser-apt-release.s3.brave.com/ stable main"
        state: present
    - name: add mullvad apt-key
      apt_key:
        url: https://repository.mullvad.net/deb/mullvad-keyring.asc
        state: present
    - name: add mullvad repo
      apt_repository:
        repo: "deb https://repository.mullvad.net/deb/stable sid main"
    - name: pre-run | update package cache (debian, etc)
      tags: always
      apt: update_cache=yes
      changed_when: False

# packages
- hosts: localhost
  become: true
  tasks:
  - name: git
    apt: name=git state=latest
  - name: kde
    apt: name=task-kde-desktop state=latest
  - name: mariadb-server
    apt: name=mariadb-server state=latest
  - name: mariadb-client
    apt: name=mariadb-client state=latest
  - name: VS Codium
    apt: name=codium state=latest
  - name: VBox Guest Additions (Utis)
    apt: name=virtualbox-guest-utils state=latest
  - name: VBox Guest Additions (X11)
    apt: name=virtualbox-guest-x11 state=latest
  - name: Install ProtonVPN
    apt: name=proton-vpn-gnome-desktop state=latest
  - name: Install ProtonVPN Gnome Applet support (1/3)
    apt: name=libayatana-appindicator3-1 state=latest
  - name: Install ProtonVPN Gnome Applet support (2/3)
    apt: name=gir1.2-ayatanaappindicator3-0.1 state=latest
  - name: Install ProtonVPN Gnome Applet support (3/3)
    apt: name=gnome-shell-extension-appindicator
  - name: Install ProtonMail Bridge (Debian)
    apt:
      deb: https://proton.me/download/bridge/protonmail-bridge_3.13.0-1_amd64.deb
  - name: Install Brave Browser
    apt: name=brave-browser state=latest
  - name: Install Mullvad Browser
    apt: name=mullvad-browser state=latest

# end of run cleanup and reporting
- hosts: localhost
  become: true
  tasks:
  - name: cleanup package cache (debian, etc)
    tags: always
    apt:
      autoclean: yes
    changed_when: false

  - name: autoremove orphan packages (debian, etc)
    tags: always
    apt:
      autoremove: yes
      purge: yes
